### ISSUE TITLE
User authentication middleware

### ISSUE THREAD

**Issue by geek-soft** [companieshouse/web-security-node#1]
Web applications commonly use middleware that checks CH session and redirect user agent to sign in page when user is not logged in. Due to the fact use case is so common it should be made reusable for other web applications.

Middleware should also use latest version of https://github.com/companieshouse/node-session-handler.

**Comment by geek-soft** [comment]
Here is snipped from appeals frontend:

```
req.session
    .ifNothing(() => loggerInstance().debug(`${AuthMiddleware.name} - handler: Session object is missing!`));

const signedIn: boolean = req.session
    .chain((session: Session) => session.getValue<ISignInInfo>(SessionKey.SignInInfo))
    .map((signInInfo: ISignInInfo) => signInInfo[SignInInfoKeys.SignedIn] === 1)
    .orDefault(false);

const userId = req.session
    .chain((session: Session) => session.getValue<ISignInInfo>(SessionKey.SignInInfo))
    .chainNullable((signInInfo: ISignInInfo) => signInInfo[SignInInfoKeys.UserProfile])
    .map((userProfile: IUserProfile) => userProfile.id)
    .extract();

if (!signedIn) {
    const redirectURI = `${getEnvOrDefault('ACCOUNT_WEB_URL', '')}/signin?return_to=${this.getReturnToPage(req)}`;
    loggerInstance().info(`${AuthMiddleware.name} - handler: userId=${userId}, Not signed in... Redirecting to: ${redirectURI}`);
    return res.redirect(redirectURI);
}

loggerInstance().debug(`${AuthMiddleware.name} - handler: userId=${userId}, Going to controller....`);
next();
```

**Comment by geek-soft** [comment]
Here is snipped from promise-to-file-web:

```
const referringPageURL = req.header("Referer") as string;

logger.debug("Check if user has referer");
if (referringPageURL === undefined) {
  logger.debug("User has no referer - redirecting to index");
  return res.redirect(pageURLs.COMPANY_REQUIRED);
}

logger.debug("Check if user is signed in");
if (!req.chSession.isSignedIn()) {

  logger.debug("User not signed in");

  let returnToUrl: string = pageURLs.COMPANY_REQUIRED;

  // if user is coming from start page
  if (referringPageURL.endsWith(pageURLs.COMPANY_REQUIRED)) {
    returnToUrl = req.originalUrl;
  }

  logger.debug("User not signed in - redirecting to login screen");
  return res.redirect("/signin?return_to=" + returnToUrl);
}

next();
```

**Comment by peadarkelly** [comment]
There is a potential security vulnerability with the post-sign-in redirect mechanism is something called [Open Redirect](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/understanding-and-discovering-open-redirect-vulnerabilities/), where the redirect url is provided in a query param.

In theory, I could send the sign in URL to another user with a malicious `return_to` value. Once they sign in, they would be redirected to the malicious site.

To test whether this vulnerability exists, try:
```
/signin?return_to=<some-non-CH-website>
i.e.
/signin?return_to=bbc.co.uk
```

If the vulnerability exists, it would be ideal if the `return_to` query param could be replaced with the [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) header.

CC @geek-soft 

DO NOT update the Accounts Sign In code as this format may be used by many Companies House services already.

**Comment by faggc** [comment]
Any code remedying an Open Redirect vulnerability would likely be implemented at the point where the return url is input. In this case I believe it should be implemented in Accounts Sign In code. Otherwise it likely wouldn't do much.

I think this is out of scope for this task since this will influence other repos using the the sign in service.

**Comment by faggc** [comment]
Is this issue good to close? @peadarkelly @geek-soft

**Comment by peadarkelly** [comment]
@faggc Fine by me.
